### ISSUE TITLE
Awesome extension 

### ISSUE THREAD

**Issue by bgarrant** [mindpixel-labs/vsc-expressionengine#1]
This extension is great. Please keep developing it. Good stuff.

**Comment by mindpixel-labs** [comment]
Thank you for the feedback! We have some more features planned for release soon.

If you have any additional feature requests please let us know.

**Comment by bgarrant** [comment]
I am so happy to be back in EE land after being away a few years. I built over 40 sites on EE2. EE5 seems really nice. Open source is also awesome for making it available to everyone. Extensions like this help so much. Thanks again.

**Comment by bgarrant** [comment]
Another cool feature would be able to autocomplete our custom field names, channel names, assets, paths, custom template names, etc. Not even sure if possible but I saw it done once in PHPStorm. Really cool if we could do that someday.

**Comment by mindpixel-labs** [comment]
Thanks! We'll definitely look into some of that more!

**Comment by mindpixel-labs** [comment]
Update: Intellisense for ExpressionEngine has been included now in this extension since about v2 I believe. V3 of this extension will drop in the coming weeks with some improvements and upgrades for the latest VSCode engine.
