### ISSUE TITLE
HTML IntelliSense Does Not Work when Extension Enabled

### ISSUE THREAD

**Issue by bgarrant** [mindpixel-labs/vsc-expressionengine#2]
Can you add the HTML IntelliSense to the extension?  When we enable the EE extension HTML IntelliSense no longer works.  It can be done as I have seen other extensions like this twig one that do both https://marketplace.visualstudio.com/items?itemName=mblode.twig-language.

Before Enabled this extension:

<img width="497" alt="Screen Shot 2019-05-22 at 5 44 06 AM" src="https://user-images.githubusercontent.com/2436728/58165149-26692480-7c55-11e9-8860-599688d410fd.png">

After Enabling it:

<img width="530" alt="Screen Shot 2019-05-22 at 5 44 30 AM" src="https://user-images.githubusercontent.com/2436728/58165159-2f59f600-7c55-11e9-805f-20926c84ad31.png">

**Comment by mindpixel-labs** [comment]
@bgarrant Thanks for the report!

Quick question. Are you using a custom extension to display those HTML tags/IntelliSense in the first screenshot or is that the default Visual Studio Code is providing?

**Comment by bgarrant** [comment]
That is the default for VS Code

**Comment by mindpixel-labs** [comment]
Great thank you. We will work on including this in the next release @bgarrant !

**Comment by bgarrant** [comment]
Thank you so much

**Comment by bgarrant** [comment]
This extension has same issue and they fixed it. Check out https://marketplace.visualstudio.com/items?itemName=mblode.twig-language. It has Twig and HTML

**Comment by bgarrant** [comment]
Pretty much all autocomplete breaks other than EE stuff. Once you add this it will be amazing! Thanks.

**Comment by mindpixel-labs** [comment]
While this still on the road map to be implemented, it currently is not possible with the way VS Code works. I will continue to review options for adding this properly though. Thank you!

**Comment by mindpixel-labs** [comment]
Update: This will now be fixed in the upcoming 3.0.0 release.
